name: Deploy Code

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Run some commands
        run: |
          npm start
          docker container ls
